from model import BertAIRegressor, ChunkedDataset, score_long_document, train
from torch.utils.data import DataLoader
from transformers import BertTokenizer

from bs4 import BeautifulSoup
import pymupdf

BATCH_SIZE = 16

def main():
    file_name = "./data/9988.pdf"
    extract_text_from_pdf_xml(file_name)
    #joined_txt = ' '.join(pageText)
    #print(pageText)
    # tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
    # model = BertAIRegressor()

    # # Example training data
    # texts = [
    #     "This is a human-written academic paragraph discussing results.",
    #     "This text was generated by an AI model and follows predictable patterns."
    # ]
    # labels = [
    #     0.0,     # human
    #     100.0    # AI
    # ]

    # dataset = ChunkedDataset(texts, labels, tokenizer)
    # dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    # #train(model, dataloader)

    # # Score a long document
    # long_text = "AI Written thing, lol"
    # ai_score = score_long_document(long_text, model, tokenizer)

    # print(f"\nFinal AI Score: {ai_score:.2f} / 100")
    return

def extract_text_from_pdf_xml(file_name):
    file_ext = file_name[-3:]
    if file_ext == "xml":
        filehandle = open(file_name)
        soup = BeautifulSoup(filehandle)
        pageText = soup.findAll(text=True)
        big_text_chunks = []
        for text in pageText:
            if len(text) > 200:
                print(text)
    elif file_ext == "pdf":
        doc = pymupdf.open(file_name) # open a document
        for page in doc: # iterate the document pages
            text = page.get_text() # get plain text encoded as UTF-8
            print(text)
    return

if __name__ == "__main__":
    main()
    